# SITE CONFIGURATION
title: Gwanlog # your site title
author: gwanwoodev # You :P
description: > # Meta description of Homepage
  MongoDB, Express.js, React.js, Node.js Developer
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://gwanwoodev.github.io" # the base hostname & protocol for your site, e.g. http://example.com
future: true
timezone: Asia/Seoul
# SEO PLUGIN
social:
  name: GwanwooPark
  links:
    - https://twitter.com
    - https://www.facebook.com/yeon.kr
    - https://www.linkedin.com/in/gwanwoodev
    - https://plus.google.com/+gwanwoodev
    - https://github.com/gwanwoodev
    - https://keybase.io/gwanwoodev

# THEME SETTINGS
navigation: # Navigation links
  - { name: "Home", link: "/" }
  - { name: "About", link: "/about" }
  - { name: "Contact", link: "/contact" }

tagline: >
  MERN Stack Developer's Blog.

hero_img: posts/emile-perron-190221_lg.jpg # Main background image: use the path from /assets/img/ => This will output /assets/img/posts/sleek_lg.jpg

email: gwanwoodev@kakao.com # email for form submission

twitter_username: gwanwoodev # replace with your_twitter_username or comment to remove link from footer
github_username: gwanwoodev # replace with your_github_username or comment to remove link from footer
instagram_username: gwanwoo.king # replace with your_instagram_username or comment to remove link from footer

disqus:
  shortname: gwanlog # to enable comments replace with your_disqus_shortname

# google_tag_manager: GTM-XXXXXXX # Uncomment to enable GTM. Replace GTM-XXXXXXX with your GTM container ID
google_tag_manager: UA-148703272-2
service_worker: false

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge # or pygments or null
# theme: jekyll-sleek # Uncomment if you're using the theme as a ruby gem
exclude:
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.jpg

include: ["_pages"]
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
